services:
  import:
    image: osb-import:latest
    build: !reset null
    network_mode: !reset null
    networks:
      - osb
    environment:
      API_BASE_URL: http://api:5003

networks:
  osb:
    name: ${OSB_NETWORK_NAME:-opensourcebuilder_default}
    external: true